### ISSUE TITLE
I have error

### ISSUE THREAD

**Issue by Tawfiqmakhamreh** [fingent-corp/gateway-woocommerce-mastercard-module#24]
Hello
I have error, how I can fix it please?

woocommerce-mastercard/vendor/monolog/monolog/src/Monolog/Logger.php on line 681

**Comment by Tawfiqmakhamreh** [comment]
Hello
im using W.P Version 6.6.2 and PHP 8.1 or8.2, this plugin when im use it, my site give error. 
this plugin work only with 6.61?

**Comment by Tawfiqmakhamreh** [comment]
any help please?

**Comment by jineshpv** [comment]
Hello Tawfiqmakhamreh,

We have resolved your plugin-related queries/issues via Service Ticket: [](https://mpgsfgs.atlassian.net/browse/FTSMPGS-870)

If you have any further questions, please feel free to raise a new ticket through the Customer Portal at [](https://mpgsfgs.atlassian.net/servicedesk/customer/portals)
