### ISSUE TITLE
Long load of the card elements when using custom gateway

### ISSUE THREAD

**Issue by mrkapable007** [fingent-corp/gateway-woocommerce-mastercard-module#25]
Hi, any possibility of resolving the long load times on order pay page when using custom gateway URL?

At the moment when using custom gateway URL, the card form elements take over 1minute to load often leading to purchase abandonment.

**Comment by jineshpv** [comment]
Hello @mrkapable007,
Could you please submit your request through the Support portal linked below? This will help us track and manage the request efficiently for internal purposes.
https://mpgsfgs.atlassian.net/servicedesk/customer/portals
Thank you!

**Comment by mrkapable007** [comment]
Thanks, i used the link.

**Comment by jineshpv** [comment]
@mrkapable007 
We believe the issue has been resolved on your end. If you have any further questions, please feel free to raise a new ticket through the Customer Portal at (https://mpgsfgs.atlassian.net/servicedesk/customer/portals)
